name: Build Modifiles

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Current Working Directory
        run: pwd

      - name: Create Windows executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile modifiles.py
          dir dist

      - name: Rename executable to overwrite
        run: |
          Move-Item dist\modifiles.exe dist\Modifiles.exe -Force  # Overwrite if it exists

      - name: Add Windows executable
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add dist\Modifiles.exe

      - name: Upload Windows executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-Windows
          path: dist\Modifiles.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements.txt

      - name: Print Current Working Directory
        run: pwd

      - name: Create macOS app
        run: |
          pip install --use-pep517 py2app
          rm -rf dist/Modifiles.app
          python setup.py py2app
          ls dist

      - name: Add macOS app
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add -f dist/Modifiles.app

      - name: Upload macOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-macOS
          path: dist/Modifiles.app 

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Current Working Directory
        run: pwd
        
      - name: Create Linux executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile modifiles.py
          ls dist

      - name: Rename Linux executable to overwrite
        run: |
          mv -f dist/Modifiles dist/ModifilesLinux  # Overwrite if it exists

      - name: Add Linux executable
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add dist/ModifilesLinux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-Linux
          path: dist/ModifilesLinux

  commit-all:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Commit all executables
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git fetch origin
          git add dist/*
          git commit -m "Add Windows, Mac, and Linux executables"
          git push origin main
