name: Build Modifiles

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Windows executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile modifiles.py

      - name: Rename executable to overwrite
        run: |
          Move-Item dist\modifiles.exe dist\Modifiles.exe -Force  # Overwrite if it exists

      - name: Commit and push Windows executable
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add dist\Modifiles.exe
          git commit -m "Add Windows executable" || echo "No changes to commit"
          git push https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com/iamaseda/Modifiles.git HEAD:main

      - name: Upload Windows executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-Windows
          path: dist\Modifiles.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements.txt

      - name: Create macOS app
        run: |
          pip install --use-pep517 py2app
          python setup.py py2app

      - name: Rename macOS app to overwrite
        run: |
          mv -f dist/modifiles.app dist/Modifiles.app  # Overwrite if it exists

      - name: Commit and push macOS app
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add -f dist/Modifiles.app
          git commit -m "Add macOS app" || echo "No changes to commit"
          git push https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com/iamaseda/Modifiles.git HEAD:main

      - name: Upload macOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-macOS
          path: dist/Modifiles.app 

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Linux executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile modifiles.py

      - name: Rename Linux executable to overwrite
        run: |
          mv -f dist/modifiles dist/Modifiles  # Overwrite if it exists

      - name: Commit and push Linux executable
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add dist/Modifiles
          git commit -m "Add Linux executable" || echo "No changes to commit"
          git push https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com/iamaseda/Modifiles.git HEAD:main

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-Linux
          path: dist/Modifiles
