name: Build Modifiles

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dist directory if it doesn't exist
        run: mkdir -p dist\windows

      - name: Print Current Working Directory
        run: |
          pwd

      - name: Create Windows executable
        run: |
          if (Test-Path "dist/windows/Modifiles.exe") {
            Remove-Item "dist/windows" -Recurse -Force
          }
          pip install pyinstaller
          pyinstaller --onefile --name Modifiles --distpath dist/windows modifiles.py
          dir dist
          dir

      - name: Add Windows executable
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add dist\windows
          git commit -m "Committing windows executable"

      - name: Upload Windows executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-Windows
          path: dist\windows\Modifiles.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements.txt

      - name: Create dist directory if it doesn't exist
        run: |
          mkdir -p dist/macos
          ls
          ls dist

      - name: Print Current Working Directory
        run: pwd

      - name: Create macOS app
        run: |
          pip install --use-pep517 py2app
          rm -rf dist/Modifiles.app
          rm -rf dist/macos/Modifiles.app
          python setup.py py2app
          ls
          ls dist
      - name: Print Current Working Directory, Dist, and Macos Directories
        run: |
          echo "Current working directory: $(pwd)"
          echo "Contents of macos (if they exist):"
          ls dist/macos || echo "Dist/macos does not exist"

      - name: Add macOS app
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add -f macos/Modifiles.app
          git commit -m "Committing macOS executable"

      - name: Upload macOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-macOS
          path: dist/macos/Modifiles.app 

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dist directory if it doesn't exist
        run: mkdir -p dist/linux

      - name: List directory
        run: |
          ls dist

      - name: Print Current Working Directory
        run: pwd

      - name: Remove Old Linux
        run: |
          rm -f dist/linux/ModifilesLinux

      - name: Create Linux executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name ModifilesLinux --distpath dist/linux modifiles.py
          ls dist
          echo "Print dist/linux:"
          ls dist/linux || echo "Dist/linux does not exist"

      - name: Add Linux executable
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git add dist/linux/ModifilesLinux
          git commit -m "Committing Linux executable"

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-Linux
          path: dist/linux/ModifilesLinux

  commit-all:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Commit all executables
        run: |
          git config --global user.email "bokyere@gmail.com"
          git config --global user.name "Asomani, Aseda"
          git fetch origin
          git status
          git add dist/
          git commit -m "Add Windows, Mac, and Linux executables"
          git push origin main
