name: Build Modifiles

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Windows executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile modifiles.py

      - name: Move executable to dist folder
        run: |
          move /Y dist/modifiles.exe dist\modifiles.exe  # Overwrite if it exists

      - name: Commit and push changes
        run: |
          git config --local user.email "bokyere@gmail.com"
          git config --local user.name "Asomani, Aseda"
          git add dist/modifiles.exe
          git commit -m "Add Windows executable" || echo "No changes to commit"
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-Windows
          path: dist/modifiles.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements.txt

      - name: Create macOS app
        run: |
          pip install --use-pep517 py2app
          python setup.py py2app

      - name: Move macOS app to dist folder
        run: |
          mv -f dist/modifiles.app dist/modifiles.app  # Overwrite if it exists

      - name: Upload macOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-macOS
          path: dist/modifiles.app 

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variable
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Using the PAT from the environment variable"
          echo "$GITHUB_PAT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Linux executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile modifiles.py

      - name: Move Linux executable to dist folder
        run: |
          mv -f dist/modifiles dist/modifiles  # Overwrite if it exists

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modifiles-Linux
          path: dist/modifiles
